App_Login/urls.py
from . import views
from django.urls import path

app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.signup, name='sign_up'),
    path('login/', views.login_page, name='login'),
    path('edit/', views.edit_profile, name='edit_profile'),
    path('logout/', views.logout_user, name='logout'),
    path('profile', views.profile, name='profile'),
    path('user/<username>/', views.user, name='user'),
    path('follow/<username>/', views.follow, name='follow'),
    path('unfollow/<username>/', views.unfollow, name='unfollow')
]

App_Posts/urls.py
from App_Posts import views
from django.urls import path

app_name = 'App_Posts'

urlpatterns = [
    path("", views.home, name="home"),
    path('liked/<pk>/', views.liked, name="liked"),
    path('unliked/<pk>/', views.unliked, name="unliked")
]

Social_Media_Project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
from App_Posts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('App_Login.urls')),
    path('post/', include('App_Posts.urls')),
    path('', views.home, name='home')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
      <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.slim.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/2f881e0bcf.js" crossorigin="anonymous"></script>
    <title>{% block title_block %} Blogs {% endblock %}</title>
        {% block css_block %}{% endblock %}
</head>
<body>
        <div class="container" style="padding: 20px">
            {% block body_block %}

            {% endblock %}
        </div>
</body>
</html>

templates/navbar.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
      <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.slim.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/2f881e0bcf.js" crossorigin="anonymous"></script>
    <title>{% block title_block %} Blogs {% endblock %}</title>
        {% block css_block %}{% endblock %}
</head>
<body>
        <nav class="navbar navbar-expand-sm bg-light navbar-light">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'App_Posts:home' %}">Home</a>
                </li>
            &nbsp;&nbsp;
                <form class="form-inline" method="GET">
                    <input class="form-control mr-sm-2" name="search" type="text" placeholder="Search">
                    <button class="btn btn-success" type="submit">Search</button>
                </form>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'App_Login:logout' %}">Logout</a>
                </li>
                <li class="nav-item">
                    {% if user.user_profile.profile_pic %}
                        <a class="nav-link" href="{% url 'App_Login:profile' %}"><img class="rounded-circle" src="/media/{{ user.user_profile.profile_pic }}" height="40px" width="40px" alt=""></a>
                        {% else %}
                        <a class="nav-link" href="{% url 'App_Login:profile' %}"><img class="rounded-circle" src="/media/profile_pics/avater.jpg" height="40px" width="40px" alt="Demo"></a>
                    {% endif %}
                </li>
            </ul>
        </nav>
        <div class="container" style="padding: 20px">
            {% block body_block %}

            {% endblock %}
        </div>
</body>
</html>