App_Login/urls.py
from . import views
from django.urls import path

app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.signup, name='sign_up'),
    path('login/', views.login_page, name='login'),
    path('edit/', views.edit_profile, name='edit_profile'),
    path('logout/', views.logout_user, name='logout'),
    path('profile', views.profile, name='profile'),
    path('user/<username>/', views.user, name='user'),
    path('follow/<username>/', views.follow, name='follow'),
    path('unfollow/<username>/', views.unfollow, name='unfollow')
]

App_Posts/urls.py
from App_Posts import views
from django.urls import path

app_name = 'App_Posts'

urlpatterns = [
    path("", views.home, name="home"),
    path('liked/<pk>/', views.liked, name="liked"),
    path('unliked/<pk>/', views.unliked, name="unliked")
]

Social_Media_Project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
from App_Posts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('App_Login.urls')),
    path('post/', include('App_Posts.urls')),
    path('', views.home, name='home')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Posts/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Posts(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post')
    image = models.ImageField(upload_to='post_images')
    caption = models.CharField(max_length=264, blank=True)
    uploaded_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-uploaded_date']


class Like(models.Model):
    post = models.ForeignKey(Posts, on_delete=models.CASCADE, related_name='Liked_post')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liker')
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{}:{}'.format(self.user, self.post)

App_Posts/forms.py
from django import forms
from App_Posts.models import Posts


class PostForm(forms.ModelForm):
    class Meta:
        model = Posts
        fields = ['image', 'caption', ]

App_Posts/views.py
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, reverse
from django.contrib.auth.decorators import login_required
from App_Login.models import Follow
from App_Posts.models import Posts, Like


# Create your views here.

@login_required
def home(request):
    search = ''
    result = ''
    following_list = Follow.objects.filter(follower=request.user)
    posts = Posts.objects.filter(author__in=following_list.values_list('following'))
    liked_post = Like.objects.filter(user=request.user)
    liked_post_list = liked_post.values_list('post', flat=True)
    if request.method == "GET":
        search = request.GET.get("search", '')
        result = User.objects.filter(username__icontains=search)
    return render(request, 'App_Posts/home.html',
                  context={'title': 'Home', 'search': search, 'result': result, 'posts': posts,
                           'liked_post_list': liked_post_list})


@login_required
def liked(request, pk):
    post = Posts.objects.get(pk=pk)
    already_liked = Like.objects.filter(post=post, user=request.user)
    if not already_liked:
        liked_post = Like(post=post, user=request.user)
        liked_post.save()
    return HttpResponseRedirect(reverse('App_Posts:home'))


@login_required
def unliked(request, pk):
    post = Posts.objects.get(pk=pk)
    already_liked = Like.objects.filter(post=post, user=request.user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('App_Posts:home'))

App_Posts/templates/App_Posts/home.html
{% extends  'navbar.html' %}
{% block title_block %}{% endblock %}
{% block body_block %}
    {% if search %}
        {% for user in result %}
            <div class="row">
                <div class="col-sm-2">
                    {% if user.user_profile.profile_pic %}
                        <img class="rounded-circle" src="/media/{{ user.user_profile.profile_pic }}" height="75px" width="75px" alt="">
                        {% else %}
                        <img class="rounded-circle" src="/media/profile_pics/avater.jpg" height="75px" width="75px" alt="Demo"></a>
                    {% endif %}
                </div>
                <div class="col-sm-10">
                    <a href="{% url 'App_Login:user' username=user.username %}">
                        {{ user.username }}
                    </a>
                    <br>
                    {{ user.user_profile.full_name }}
                </div>
            </div>
        <br>
        {% endfor %}
    	{% else %}
        <div class="row">
        <div class="col-sm-8">
                {% for post in posts %}
                    <div style="border: 1px solid #888">
                        <div style="padding: 10px">
                            {% if post.author.user_profile.profile_pic %}
                                <img src="/media/{{ post.author.user_profile.profile_pic }}" width="40px" height="40px" class="rounded-circle" alt="">
                            {% else %}
                                <img src="/media/profile_pics/avater.jpg" width="40px" height="40px" class="rounded-circle" alt="">
                            {% endif %}
                            <a href="{% url 'App_Login:user' username=post.author %}">{{ post.author }}</a>
                        </div>
                        <br>
                        <img src="/media/{{ post.image }}"  width="100%" alt="">
                        <div style="padding: 20px">
                            <p>{{ post.caption|linebreaks }}</p>
                            {{ post.Liked_post.count }} likes <br>
                            {% if post.pk in liked_post_list %}
                                <a href="{% url 'App_Posts:unliked' pk=post.pk %}"><i class="fa fa-heart" style="font-size: 36px"></i></a>
                            {% else %}
                                <a href="{% url 'App_Posts:liked' pk=post.pk %}"><i class="fa fa-heart-o" style="font-size: 36px"></i></a>
                            {% endif %}
                        </div>
                    </div>
                    <br><br>
                {% endfor %}
        </div>
        <div class="col-sm-4">
            <div class="row">
                <div class="col-sm-4">
                    {% if user.user_profile.profile_pic %}
                        <img class="rounded-circle" src="/media/{{ user.user_profile.profile_pic }}" height="75px" width="75px" alt="">
                    {% else %}
                        <img class="rounded-circle" src="/media/profile_pics/avater.jpg" height="75px" width="75px" alt="Demo"></a>
                    {% endif %}
                </div>
                <div class="col-sm-8">
                    {{ user.username }}
                    <br>
                    {{ user.user_profile_full_name }}
                </div>
            </div>
        </div>
        </div>
    {% endif %}
{% endblock %}